#!/bin/bash -e
function get_module() {
  local path=$1;
  while true; do
    path=$(dirname $path);
    if [ -f "$path/pom.xml" ]; then
      echo "$path";
      return;
    elif [[ "./" =~ "$path" ]]; then
      return;
    fi
  done
}

modules=();

for file in $(git diff --name-only --cached \*.java); do
  module=$(get_module "$file");
  if [ "" != "$module" ] \
      && [[ ! " ${modules[@]} " =~ " $module " ]]; then
    modules+=("$module");
  fi
done;

if [ ${#modules[@]} -eq 0 ]; then
  exit;
fi

modules_arg=$(printf ",%s" "${modules[@]}");
modules_arg=${modules_arg:1};

export MAVEN_OPTS="-client
  -XX:+TieredCompilation
  -XX:TieredStopAtLevel=1
  -Xverify:none";

echo -e "\033[1;31m Please wait $modules_arg check...\033[0m"
echo -e "\033[1;32m mvn apache-rat:check\033[0m"
mvn -q -pl "$modules_arg" apache-rat:check;
echo -e "\033[1;33m mvn spotless:apply\033[0m"
mvn -q -pl "$modules_arg" spotless:apply;
echo -e "\033[1;34m mvn spotless:check\033[0m"
mvn -q -pl "$modules_arg" spotless:check;
echo -e "\033[1;35m mvn checkstyle:check\033[0m"
mvn -q -pl "$modules_arg" checkstyle:check;
